(function(){
  var q = new URLSearchParams(location.search), R = {errors:[]}, W = function(ms){ return new Promise(function(r){ setTimeout(r, ms); }); };
  window.addEventListener('error', function(e){ R.errors.push('err: '+e.message); });
  window.addEventListener('unhandledrejection', function(e){ R.errors.push('rej: '+String(e.reason && e.reason.message || e.reason).slice(0,200)); });
  function out(){ var p=document.createElement('pre'); p.id='__probe'; p.textContent=JSON.stringify(R); document.body.appendChild(p); }
  var E = function(c){ return window.__appEval(c); };
  function snapNode(){
    return E("(function(){ var ids=Object.keys(chatTree.nodes).filter(function(k){return chatTree.nodes[k].role==='assistant'}); var n=chatTree.nodes[ids[ids.length-1]]; if(!n) return null; " +
      "return {isGenerating:n.isGenerating, versions:n.versions.map(function(v){ return {raw:(v.rawContent||'').slice(0,40)+'…'+(v.rawContent||'').slice(-20), len:(v.rawContent||'').length, dead:v.isDead, err:v.errorText||null, end:!!v.endTime, tev:(v._toolEvents||[]).length, usage:v.metadata&&v.metadata.usage&&{input:v.metadata.usage.input,output:v.metadata.usage.output}, cost:v.metadata&&v.metadata.cost&&v.metadata.cost.calculated&&v.metadata.cost.calculated.total, bal:!!(v.metadata&&v.metadata.balance)}; }), gens:Object.keys(gens), ctrls:activeControllers.size, work:!!work()}; })()");
  }
  async function send(text){ E("els.messageInput.value="+JSON.stringify(text)+"; updateSendBtn();"); R.sendEnabled = !document.getElementById('sendBtn').disabled; E("sendMessage()"); }
  window.addEventListener('load', function(){ setTimeout(async function(){
    try {
      var js = q.get('js'), sc = q.get('scenario');
      var sc0=q.get('scenario');
      if (sc0 === 'life'){ window.__L={ls:new Map(), iv:new Set(), obs:new Set()}; var L=window.__L; var ae=EventTarget.prototype.addEventListener, re=EventTarget.prototype.removeEventListener; var lk=function(t,ty,f,o){ return ty+'|'+(t===window?'win':t===document?'doc':t===document.body?'body':(t&&t.id)||(t&&t.nodeName)||'?')+'|'+(!!(o===true||(o&&o.capture))); }; EventTarget.prototype.addEventListener=function(ty,f,o){ if(f){ var k=lk(this,ty,f,o); var m=L.ls.get(k)||new Set(); m.add(f); L.ls.set(k,m);} return ae.apply(this,arguments); }; EventTarget.prototype.removeEventListener=function(ty,f,o){ var m=L.ls.get(lk(this,ty,f,o)); if(m) m.delete(f); return re.apply(this,arguments); }; var si=window.setInterval, ci=window.clearInterval; window.setInterval=function(){ var id=si.apply(window,arguments); L.iv.add(id); return id; }; window.clearInterval=function(id){ L.iv.delete(id); return ci.apply(window,arguments); }; var MO=window.MutationObserver; var ob=MO.prototype.observe, dc=MO.prototype.disconnect; MO.prototype.observe=function(){ L.obs.add(this); return ob.apply(this,arguments); }; MO.prototype.disconnect=function(){ L.obs.delete(this); return dc.apply(this,arguments); }; var RO=window.ResizeObserver; if(RO){ var rob=RO.prototype.observe, rdc=RO.prototype.disconnect; RO.prototype.observe=function(){ L.obs.add(this); return rob.apply(this,arguments); }; RO.prototype.disconnect=function(){ L.obs.delete(this); return rdc.apply(this,arguments); }; } }
      window.__orig0={}; ['executeAPI','buildAPIMessages','formatMarkdown','buildCodeBlockHTML','applyResponseMetadata','renderFullChat','finalizeGeneration','triggerAI','resetStopBtn','updateSendBtn','saveHistory','saveHotMirror','createNode','generateAIResponse','sendMessage','run','loadModels','fetchModels','updateNodeDOM','createMessageDOM','getCurrentModel','getApiKey'].forEach(function(n){ try{ window.__orig0[n]=E(n); }catch(e){} });
      window.__mockFetch0=window.fetch; if (sc0==='life'){ R.base={}; window.__L.ls.forEach(function(m,k){ if(m.size) R.base[k]=m.size; }); }
      if (js){ var src = await (await fetch(js)).text(); E(src); await W(2500); }
      if (q.get('reinstall') && window.__eval1){ window.__eval1.disable(); await W(500); E(src); await W(2500); }
      if (q.get('balanceSnap') && window.__eval1){ window.__eval1.config.balanceSnap = true; }
      R.model = E("getCurrentModel()"); R.provider = E("activeProviderId");
      if (sc === 'surface'){ var E1=window.__eval1||{}; R.fns=Object.keys(E1).filter(function(k){return typeof E1[k]==='function';}).sort(); R.props=Object.keys(E1).filter(function(k){return typeof E1[k]!=='function';}).sort(); R.cfg=E1.config&&Object.keys(E1.config).sort(); R.cfgv=E1.config; R.flags=E1.FLAGS||E1.flags; R.tools=Object.keys(window.__tools||{}).sort(); R.styles=[].map.call(document.querySelectorAll('style[id]'),function(s){return s.id;}).sort(); R.ids=[].map.call(document.querySelectorAll('[id]'),function(s){return s.id;}).filter(function(i){return /exp|eval1|dse|peak|pill|bal/i.test(i);}).sort(); R.expRows=document.querySelectorAll('#tab-exp .setting-row').length; R.expTabs=[].map.call(document.querySelectorAll('#tab-exp .tab-btn, #tab-exp button[data-sub]'),function(b){return b.textContent;}); R.win=Object.keys(window).filter(function(k){return /^__|dse|eval1/i.test(k);}).sort(); R.hostFns=['executeAPI','buildAPIMessages','formatMarkdown','buildCodeBlockHTML','applyResponseMetadata','renderFullChat','finalizeGeneration','triggerAI','resetStopBtn','updateSendBtn','saveHistory','saveHotMirror','createNode','generateAIResponse','sendMessage','run','loadModels','fetchModels','updateNodeDOM','createMessageDOM','getCurrentModel'].filter(function(n){ try{ return E(n)!==E('window.__origProbe&&0')&&E(n).toString().length< 0; }catch(e){return false;} }); R.patched={}; ['executeAPI','buildAPIMessages','formatMarkdown','buildCodeBlockHTML','applyResponseMetadata','renderFullChat','finalizeGeneration','triggerAI','resetStopBtn','updateSendBtn','saveHistory','saveHotMirror','createNode','generateAIResponse','sendMessage','run','loadModels','fetchModels','updateNodeDOM','createMessageDOM','getCurrentModel','getApiKey'].forEach(function(n){ try{ R.patched[n]= E(n)!==window.__orig0[n]; }catch(e){ R.patched[n]='err'; } }); R.pill=(document.getElementById('eval1Pill')||{}).textContent; R.provJSON=E("JSON.stringify(providers.deepseek).length"); R.dsModels=E("Object.keys(providers.deepseek.fallbackModels||{})"); R.dsDefault=E("providers.deepseek.defaultModel"); }
      if (sc === 'chat'){ if (q.get('respIn')) window.__mockCfg.respIn=+q.get('respIn'); if (q.get('repeat')) window.__mockCfg.repeatUsage=true; var txt=q.get('text')||'hi'; if (q.get('model')) { E("els.modelSelect.innerHTML+='<option>"+q.get('model')+"</option>'; els.modelSelect.value="+JSON.stringify(q.get('model'))); } R.model2=E("getCurrentModel()"); await send(txt); await W(+(q.get('wait')||8000)); R.node = snapNode(); R.calls = window.__mockLog.filter(function(l){return l.method==='POST';}).map(function(l){ var b=l.body||{}; return l.url.replace(/https:\/\/[^/]+/,'')+' tools='+((b.tools||[]).map(function(t){return t.name||(t.function&&t.function.name)||t.type;}).join(','))+' model='+b.model; }); R.text=E("(function(){ var ids=Object.keys(chatTree.nodes).filter(function(k){return chatTree.nodes[k].role==='assistant'}); var n=chatTree.nodes[ids[ids.length-1]]; return n&&n.versions[n.activeVersion].rawContent; })()"); R.meta=E("(function(){ var ids=Object.keys(chatTree.nodes).filter(function(k){return chatTree.nodes[k].role==='assistant'}); var n=chatTree.nodes[ids[ids.length-1]]; var v=n&&n.versions[n.activeVersion]; return v&&{usage:v.metadata&&v.metadata.usage, cost:v.metadata&&v.metadata.cost, tools:v.metadata&&v.metadata.tools, toolBatch:v.toolBatch, tokens:v.tokens, promptTokens:v.promptTokens}; })()"); R.dom=(document.querySelector('.message.assistant:last-child .bubble')||{}).innerHTML; R.dom = R.dom && R.dom.replace(/\s+/g,' ').slice(0,600); }
      if (sc === 'life'){ var L=window.__L; var H=['executeAPI','buildAPIMessages','formatMarkdown','buildCodeBlockHTML','applyResponseMetadata','renderFullChat','finalizeGeneration','triggerAI','resetStopBtn','updateSendBtn','saveHistory','saveHotMirror','sendMessage','loadModels','fetchModels'];
        var snap=function(){ var ls=0, per={}; L.ls.forEach(function(m,k){ if(m.size){ ls+=m.size; per[k]=m.size; } }); return {ls:ls, per:per, iv:L.iv.size, obs:L.obs.size, styles:[].map.call(document.querySelectorAll('style[id]'),function(x){return x.id;}).length, expTab:!!document.getElementById('tab-exp'), pill:!!document.getElementById('eval1Pill'), fetchPatched: window.fetch!==window.__mockFetch0, hostPatched:H.filter(function(n){ try{ return E(n)!==window.__orig0[n]; }catch(e){ return true; } }), timer:!!document.getElementById('dse-peak-timer') }; };
        R.loaded=snap(); window.__eval1.disable(); await W(800); R.disabled=snap(); E(src); await W(2500); R.reloaded=snap(); window.__eval1.disable(); await W(800); R.disabled2=snap(); E(src); await W(2500); R.reloaded2=snap();
        await send('USE_TOOL please'); await W(9000); R.node=snapNode(); R.calls=window.__mockLog.filter(function(l){return l.method==='POST';}).length;
        var diff=function(a,b){ var o={}; Object.keys(Object.assign({},a,b)).forEach(function(k){ if((a[k]||0)!==(b[k]||0)) o[k]=[(a[k]||0),(b[k]||0)]; }); return o; };
        R.lsGrowth_loaded_vs_reloaded2=diff(R.loaded.per,R.reloaded2.per); R.lsLeft_after_disable=diff(R.base||{},R.disabled.per); ['loaded','disabled','reloaded','disabled2','reloaded2'].forEach(function(k){ delete R[k].per; });
      }
      if (sc === 'autosrc'){ if (q.get('re')){ window.__eval1.disable(); await W(500); E(src); await W(2500); } window.__eval1.config.autoSourceOn = q.get('on')?true:false; R.src0=E("providers.deepseek.source"); E("openRegistryEditor('provider', providers.deepseek, 'deepseek')"); var o=JSON.parse(document.getElementById('provJsonText').value); o.name='DeepSeek X'; document.getElementById('provJsonText').value=JSON.stringify(o); document.getElementById('saveProvJsonBtn').click(); await W(1500); R.src1=E("providers.deepseek.source"); R.name=E("providers.deepseek.name"); R.cfgOn=window.__eval1.config.autoSourceOn; }
      if (sc === 'fetchrest'){ R.before=String(window.fetch).slice(0,80); R.eqMock0=window.fetch===window.__mockFetch0; window.__eval1.disable(); await W(500); R.after=String(window.fetch).slice(0,120); R.afterEqMock=window.fetch===window.__mockFetch0; E("els.messageInput.value='hi'; updateSendBtn(); sendMessage()"); await W(4000); R.calls=window.__mockLog.filter(function(l){return l.method==='POST';}).map(function(l){return l.url;}); }
      if (sc === 'abortInTool'){ window.__mockCfg.toolCode="var t=Date.now(); while(Date.now()-t<1500){} 1"; await send('USE_TOOL please'); R.abortedAt=null; for (var k=0;k<600;k++){ await W(10); var posts=window.__mockLog.filter(function(l){return l.method==='POST'}).length; var raw=E("(function(){ var ids=Object.keys(chatTree.nodes).filter(function(k){return chatTree.nodes[k].role==='assistant'}); var n=chatTree.nodes[ids[ids.length-1]]; return n?n.versions[0].rawContent:''; })()")||''; if (posts===1 && window.__mockCfg.closed===1){ await W(200); R.abortedAt=k*10; E("activeControllers.forEach(function(c){c.abort()})"); break; } } await W(8000); R.node=snapNode(); R.posts=window.__mockLog.filter(function(l){return l.method==='POST'}).length; R.stopBtn=getComputedStyle(document.getElementById('stopBtn')).display; R.text=E("(function(){ var ids=Object.keys(chatTree.nodes).filter(function(k){return chatTree.nodes[k].role==='assistant'}); var n=chatTree.nodes[ids[ids.length-1]]; return n.versions[0].rawContent; })()"); }
      if (sc === 'chainAbort'){ window.__mockCfg.toolCode="var t=Date.now(); while(Date.now()-t<1500){} 1"; E("agents.chainA={id:'chainA',on:1,next:'chainB'}; agents.chainB={id:'chainB',on:1}"); E("(function(){ var u=createNode('user','USE_TOOL please','', (getViewNodes().at(-1)||{}).id||'root'); window.__gr=generateAIResponse(u.id,null,'chainA'); window.__gr.then(function(x){ window.__grv=x; }); })()"); for (var k=0;k<600;k++){ await W(10); if (window.__mockCfg.closed===1){ await W(200); E("activeControllers.forEach(function(c){c.abort()})"); break; } } await W(8000); R.ret=window.__grv; R.posts=window.__mockLog.filter(function(l){return l.method==='POST'}).length; R.assistants=E("Object.values(chatTree.nodes).filter(function(n){return n.role==='assistant'}).length"); }
      if (sc === 'tool'){ await send('USE_TOOL please'); await W(8000); R.node = snapNode(); R.calls = window.__mockLog.filter(function(l){return l.method==='POST';}).map(function(l){return l.url.replace(/https:\/\/[^/]+/,'');}); }
      if (sc === 'usage'){ window.__mockCfg.repeatUsage = true; await send('hi'); await W(6000); R.node = snapNode(); }
      if (sc === 'usage1'){ await send('hi'); await W(6000); R.node = snapNode(); }
      if (sc === 'abortTool'){ window.__mockCfg.delayMs = 1500; await send('USE_TOOL please'); await W(1700); /* first round done? */ await W(100); E("activeControllers.forEach(function(c){c.abort()})"); await W(4000); R.node = snapNode(); }
      if (sc === 'abortStream'){ window.__mockCfg.delayMs = 3000; await send('hi'); await W(1000); E("activeControllers.forEach(function(c){c.abort()})"); await W(3000); R.node = snapNode(); }
      if (sc === 'swarm2'){ window.__mockCfg.delayMs = 20000; E("generateAIResponse(null, undefined, {batch:[0.3,0.7]})"); R.t=[]; for (var i=0;i<9;i++){ await W(10000); var s=snapNode(); R.t.push({t:(i+1)*10, posts:window.__mockLog.filter(function(l){return l.method==='POST'}).length, v:s.versions.map(function(v){return (v.dead?'D':'')+(v.end?'E':'')+v.len}), gens:s.gens.length, ctrls:s.ctrls, sops:E('Object.keys(streamOps).length'), saving:E('isSaving'), wts:E('Object.keys(waitingToSave).length'), clash:E('isClashModalOpen')}); } }
      if (sc === 'swarm3'){ window.__mockCfg.delayMs = 20000; E("generateAIResponse(null, undefined, {batch:[0.3,0.7]})"); await W(150000); var s=snapNode(); R.final={v:s.versions.map(function(v){return (v.dead?'D':'')+(v.end?'E':'')+v.len+(v.err?':'+v.err:'')}), gens:s.gens, ctrls:s.ctrls, work:s.work, sops:E('Object.keys(streamOps).length')}; E("treeAction(async function(){ window.__ta=1 },'probe')"); await W(3000); R.treeActionRan=!!window.__ta; }
      if (sc === 'finTwice'){ R.r = E("(function(){ var n=createNode('assistant','','', 'root', true); var k=genKey(n.id,0); n.versions[0].startTime=Date.now(); finalizeGeneration(n,0); /* early finalize, e.g. reconciler */ gens[k]={key:k,node:n,parent:chatTree.nodes.root,tree:chatTree,v:0,done:0}; n.versions[0].endTime=Date.now(); finalizeGeneration(n,0); /* the real end */ return {gensLeft: Object.keys(gens).length, work: !!work()}; })()"); }
      if (sc === 'swarm18'){ window.__mockCfg.delayMs = 20000; E("generateAIResponse(null, undefined, {batch:[0.3,0.7]})"); await W(18000); var s=snapNode(); R.at18={v:s.versions.map(function(v){return (v.dead?'D':'')+(v.end?'E':'')+v.len+(v.err?':'+v.err:'')}), gens:s.gens.length}; }
      if (sc === 'abortTool2'){ window.__mockCfg.delayMs = 1500; await send('USE_TOOL please'); await W(1800); E("activeControllers.forEach(function(c){c.abort()})"); await W(20000); R.node = snapNode(); R.stopBtn=getComputedStyle(document.getElementById('stopBtn')).display; R.posts=window.__mockLog.filter(function(l){return l.method==='POST'}).length; }
      if (sc === 'fail'){ window.__mockCfg.fail = 500; E("(async function(){ var u=createNode('user','hi','', (getViewNodes().at(-1)||{}).id||'root'); var a=createNode('assistant','','',u.id,true); window.__tr = await triggerAI(buildAPIMessages(getViewNodes()), a, 0, run()); })()"); await W(6000); R.triggerAIreturned = window.__tr; R.node = snapNode(); }
      if (sc === 'tier'){ R.r = E("(function(){ var r=run(null,{provider:'openai', model:'gpt-5.6-sol'}); function c(u){ var v={}; applyResponseMetadata(v,u,r); return qv(v.metadata.cost.calculated.total); } var per=[1,2,3].map(function(){ return c({prompt_tokens:100000, completion_tokens:1000}); }); var sum=per.reduce(function(a,b){return a+b},0); var cum=c({prompt_tokens:300000, completion_tokens:3000}); return {sumOfTurns:+sum.toFixed(6), cumulativeAsOne:+cum.toFixed(6), ratio:+(cum/sum).toFixed(3)}; })()"); }
      if (sc === 'pe97'){ var PE=window.__pricingEngine; R.r={}; ['gpt-5.6-sol','gemini-3.1-pro-preview','gemini-3.6-flash','glm-5.2','deepseek-v4-pro','deepseek-flash'].forEach(function(m){ try{ R.r[m]={ctx0:PE.priceAt(m,Date.now(),0), ctx300k:PE.priceAt(m,Date.now(),300000), cost:E("(function(){ var r=run(null,{model:'"+m+"', provider:(function(){ for (var k in providers){ var fm=providers[k].fallbackModels; if(fm && !Array.isArray(fm) && fm['"+m+"']) return k;} })()}); var v={}; applyResponseMetadata(v,{prompt_tokens:100000,completion_tokens:1000},r); return v.metadata.cost.calculated.total; })()")}; }catch(e){ R.r[m]='err '+e; } }); }
      if (sc === 'swarm'){ window.__mockCfg.delayMs = 20000; E("generateAIResponse(null, undefined, {batch:[0.3,0.7]})"); await W(18000); R.at18s = snapNode(); await W(30000); R.node = snapNode(); }
      if (sc === 'paint' && window.__eval1){ window.__eval1.setPaintInterval(1000); R.paint = {paintInterval: window.__eval1.config.paintInterval, paintIntervalMs: window.__eval1.config.paintIntervalMs}; }
    } catch(e){ R.errors.push('probe: '+(e && e.stack || e)); }
    out();
  }, 1500); });
})();
